apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: acrgowthamdevops.azurecr.io/api-gateway:v1
        ports:
        - containerPort: 3000