apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: acrgowthamdevops.azurecr.io/order-service:v1
        ports:
        - containerPort: 3003